task: "hearing"
eeg:
  sound_files: ["babycry", "chewing", "engine", "seawave", "typing"]
  baseline_duration: 15
  stimuli_repeat: 5
  stimulus_dration: 4
  response_duration: 5
  rest_range: [6, 8]
fnirs:
  sound_files: ["babycry", "chewing", "engine", "seawave", "typing"]
  baseline_duration: 30
  stimuli_repeat: 3
  stimulus_dration: 4
  response_duration: 6
  rest_range: [8, 12]
test:
  sound_files: ["babycry", "seawave"]
  baseline_duration: 5
  stimuli_repeat: 1
  stimulus_dration: 4
  response_duration: 4
  rest_range: [2, 3]
hearing:
  prestim: &prestim_value 5
  pmt_prestim: *prestim_value
  pmt_stim: 2
  pmt_poststim: 5
  pmt_trials: 4
  hlt_prestim : 5
  hlt_stim: 2
  hlt_poststim: 5
  hlt_trials: 4
  let_prestim : 5
  let_stim: 2
  let_poststim: 5
  let_trials: 4
  ast_prestim: 5
  ast_stim: 6
  ast_poststim: 5
  ast_trials: 4