task: "hearing"
test:
  pmt_prestim: 1
  pmt_stim: 1
  pmt_poststim: 1
  pmt_trials: 1
  hlt_prestim : 1
  hlt_stim: 1
  hlt_poststim: 1
  hlt_trials: 1
  let_prestim : 1
  let_stim: 1
  let_poststim: 1
  let_trials: 1
  ast_prestim: 1
  ast_stim: 5
  ast_poststim: 1
  ast_trials: 1
hearing:
  prestim: &prestim_value 5
  stim: &stim_value 2
  poststim: &poststim_value 5
  pmt_prestim: *prestim_value
  pmt_stim: *stim_value
  pmt_poststim: *poststim_value
  pmt_trials: 5
  hlt_prestim : *prestim_value
  hlt_stim: *stim_value
  hlt_poststim: *poststim_value
  hlt_trials: 5
  let_prestim : *prestim_value
  let_stim: *stim_value
  let_poststim: *poststim_value
  let_trials: 5
  ast_prestim: *prestim_value
  ast_stim: 5
  ast_poststim: *poststim_value
  ast_trials: 5